[package]
name = "lib31corefs"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["31core <31core@tutanota.com>"]

[lib]
path = "src/lib.rs"

[dependencies]
uuid = { version = "1.15.1", features = ["v4"] }
