[package]
name = "label"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "31corefs-label"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
lib31corefs = { path = "../../lib31corefs" }
